name: Generate Snake Animation

on:
  workflow_dispatch:  # تقدر تشغله يدويًا من Actions
  schedule:
    - cron: "0 0 * * *"  # اختياري، يوميًا عند منتصف الليل

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: mazenessam99
          outputs: github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          folder: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
