name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight (UTC)
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write   # allow writing to repo (needed for push)

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake (SVG)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mazenessam99
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit generated files and push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "chore: update github contribution snake"
          add: "dist/**"
          push: true
          branch: output
